CREATE MATERIALIZED VIEW IF NOT EXISTS GROUPS_MATERIALIZED_VIEW AS SELECT * FROM entities.GROUPS;

CREATE MATERIALIZED VIEW IF NOT EXISTS LESSONS_MATERIALIZED_VIEW AS SELECT * FROM entities.LESSONS;

CREATE MATERIALIZED VIEW IF NOT EXISTS TEACHERS_MATERIALIZED_VIEW AS SELECT * FROM entities.TEACHERS;

CREATE MATERIALIZED VIEW IF NOT EXISTS COMMENTS_MATERIALIZED_VIEW AS SELECT * FROM entities.COMMENTS;

CREATE MATERIALIZED VIEW IF NOT EXISTS STUDENTS_MATERIALIZED_VIEW AS SELECT * FROM entities.STUDENTS;

CREATE MATERIALIZED VIEW IF NOT EXISTS HOMEWORK_MATERIALIZED_VIEW AS SELECT * FROM entities.HOMEWORK;

CREATE MATERIALIZED VIEW IF NOT EXISTS STUDENT_MARKS_MATERIALIZED_VIEW AS SELECT * FROM entities.STUDENT_MARKS;

CREATE MATERIALIZED VIEW IF NOT EXISTS EDUCATION_DIRECTIONS_MATERIALIZED_VIEW AS SELECT * FROM entities.EDUCATION_DIRECTIONS;