CREATE STATISTICS IF NOT EXISTS UNIVERSITY_GROUPS_TABLE_STATISTICS ( MCV ) ON group_name, students_number FROM entities.GROUPS;

CREATE STATISTICS IF NOT EXISTS UNIVERSITY_LESSON_TABLE_STATISTICS ( DEPENDENCIES ) ON lesson_name, lesson_status FROM entities.LESSONS;

CREATE STATISTICS IF NOT EXISTS UNIVERSITY_TEACHERS_TABLE_STATISTICS ( NDISTINCT ) ON id, email, phone_number, name FROM entities.TEACHERS;

CREATE STATISTICS IF NOT EXISTS UNIVERSITY_STUDENTS_TABLE_STATISTICS ( NDISTINCT ) ON id, email, phone_number, name FROM entities.STUDENTS;

CREATE STATISTICS IF NOT EXISTS UNIVERSITY_STUDENT_APPEARANCE_TABLE_STATISTICS ( DEPENDENCIES ) ON created_date, lesson_appearance_types FROM entities.STUDENT_APPEARANCE_IN_LESSONS;