package com.example.fido.constants.cassandra;

public enum Details {
    ARD_102, SELF_EMPLOYMENT, FREE, ESCORT, ESCORT_CAR,

    FIND_FACE_PERSON, FIND_FACE_CAR, // FOR TASKS FROM ASSOMIDDIN
    FIND_FACE_EVENT_BODY, FIND_FACE_EVENT_CAR, FIND_FACE_EVENT_FACE,

    // for Card
    DETAILS, ADDRESS_OF_APPLICANT, APPLICANT_DATA, ADDRESS_OF_INCIDENT, DATA_OF_VICTIM, ADDRESS_OF_VICTIM, ADDITIONAL_ADDRESS, ADDITIONAL_ADDRESS_OF_APPLICANT, ADDITIONAL_ADDRESS_OF_Victim,

    // for SElfEmployment
    NUMBER, ACCEPTED_TIME, ACCEPTED_POINT_LATITUDE, ACCEPTED_POINT_LONGITUDE, ARRIVED_TIME, ARRIVED_POINT_LATITUDE,
    ARRIVED_POINT_LONGITUDE, REPORT, REPORT_TIME, DESCRIPTION, ADDRESS,

    // FOR CAR_TOTAL_DATA
    TEX_PASSPORT, TONIROVKA, AVTO_SUGURTA, ISHONCHNOMA, NOMIDAGI_MAVJUD_TRANSPORT_VOSITALAR
}
